src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }
  
  get "weight_entries/index"
  root "weight_entries#index"
  resources :weight_entries
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :weight_entries, dependent: :destroy

  def self.from_google(u)
    create_with(uid: u[:uid], provider: 'google', password: Devise.friendly_token[0, 20]).find_or_create_by!(email: u[:email])
  end
end

src/app/models/weight_entry.rb
class WeightEntry < ApplicationRecord
    belongs_to :user
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def after_sign_in_path_for(resource)
		weight_entries_path # Remplacez par la page souhaitée 
	end
end

src/app/controllers/omniauth_callbacks_controller.rb
# app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_google(from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:notice] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

   def from_google_params
     @from_google_params ||= {
       uid: auth.uid,
       email: auth.info.email
     }
   end

   def auth
     @auth ||= request.env['omniauth.auth']
   end
end

src/app/controllers/weight_entries_controller.rb
class WeightEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_weight_entry, only: [:show, :edit, :update, :destroy]

  def index
    @weight_entries = current_user.weight_entries.order(date: :desc)
  end

  def new
    @weight_entry = current_user.weight_entries.new(date: Date.current)
  end

  def create
    @weight_entry = current_user.weight_entries.new(weight_entry_params)
    if @weight_entry.save
      redirect_to weight_entries_path, notice: 'Votre suivi de poids a été ajouté avec succes.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @weight_entry.update(weight_entry_params)
      redirect_to weight_entries_path, notice: 'votre suivi a été mis a jour'
    else
      render :edit
    end
  end

  def destroy
    @weight_entry.destroy
    redirect_to weight_entries_path, notice: 'votre suivi a été supprimé'
  end

  private
  def set_weight_entry
    @weight_entry = current_user.weight_entries.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to weight_entries_path, alert: 'Entrée introuvable'
  end

    def weight_entry_params
      params.require(:weight_entry).permit(:date, :weight, :steps)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/weight_entries_helper.rb
module WeightEntriesHelper
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div classe="container mx-auto p-6">
      <div role="alert">
        <strong classe="font-bold">Succés1</strong>
        <span classe="block sm:inline"><%= flash[:notice]%></span>
      </div>
    </div>
    <% end %>

    <main class="container mx-auto mt-28 px-5">
      <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

      <%= yield %>
    </main>
  </body>
</html>

src/app/views/weight_entries/edit.html.erb
<div class="flex justify-center items-center">
    <div class="bg-white p-8 rounded-xl shadow-lg w-full max-w-md">
        <h1 class="text-2xl font-bold text-gray-800 mb-4 text-center">Édition</h1>
        
        <p class="text-gray-600">Poids original : <span class="font-semibold text-gray-800"><%= @weight_entry.weight %></span></p>
        <p class="text-gray-600">Pas original: <span class="font-semibold text-gray-800"><%= @weight_entry.steps %></span></p>
        <p class="text-gray-600 mb-4">Date originale : <span class="font-semibold text-gray-800"><%= @weight_entry.date %></span></p>
        
        <%= form_with(model: @weight_entry, local: true) do |form| %>
            <% if @weight_entry.errors.any? %>
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
                    <h4 class="font-bold">Erreur</h4>
                    <ul class="list-disc pl-5">
                        <% @weight_entry.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        
            <div class="mb-4">
                <%= form.label :weight, class: "block text-gray-700 font-bold mb-2" %>
                <%= form.number_field :weight, step: "0.1", placeholder: "Entrez votre poids", class: "w-full p-2 border rounded-md focus:ring focus:ring-blue-300" %>
            </div>

            <div class="mb-4">
                <%= form.label :steps, class: "block text-gray-700 font-bold mb-2"%>
                <%= form.number_field :steps, placeholder: "Entrez votre nombre de pas", class: "w-full p-2 border rounded-md focus:ring focus:ring-blue-300"%>
            </div>
        
            <div class="mb-4">
                <%= form.label :date, class: "block text-gray-700 font-bold mb-2" %>
                <%= form.date_field :date, placeholder: "Entrez la date de votre suivi de poids", class: "w-full p-2 border rounded-md focus:ring focus:ring-blue-300" %>
            </div>
        
            <div class="flex justify-end gap-2">
                <%= form.submit "Enregistrer", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>
                <%= link_to 'Retour', weight_entries_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>
            </div>
        <% end %>
    </div>
</div>

src/app/views/weight_entries/index.html.erb
<%# app/views/weight_entries/index.html.erb %>
<div class="container mx-auto p-6">
  <h1 class="text-4xl font-bold text-center text-blue-600 mb-6">Traqueur de Poids et Pas</h1>
  <!-- Bouton de déconnexion -->
  <div class="flex justify-end mb-5">
      <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>
  </div>
  <div class="flex justify-end mb-4">
    <%= link_to "Ajouter une nouvelle entrée", new_weight_entry_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
  <div class="overflow-x-auto">
    <table class="min-w-full bg-white shadow-md rounded-lg">
      <thead>
        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
          <th class="py-3 px-6 text-left">Date</th>
          <th class="py-3 px-6 text-left">Poids (kg)</th>
          <th class="py-3 px-6 text-left">Pas</th>
          <th class="py-3 px-6 text-center">Actions</th>
        </tr>
      </thead>
      <tbody class="text-gray-600 text-sm font-light">
        <% @weight_entries.each do |entry| %>
          <tr class="border-b border-gray-200 hover:bg-gray-100">
            <td class="py-3 px-6 text-left"><%= entry.date %></td>
            <td class="py-3 px-6 text-left"><%= entry.weight %></td>
            <td class="py-3 px-6 text-left"><%= entry.steps %></td>
            <td class="py-3 px-6 text-center flex justify-center">
              <%= link_to "Voir", weight_entry_path(entry), class: "text-blue-500 hover:underline" %> |
              <%= link_to "Modifier", edit_weight_entry_path(entry), class: "text-green-500 hover:underline" %> |
              <%= button_to weight_entry_path(entry), method: :delete, form: { data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette entrée ?" } }, class: "text-red-500 hover:underline", title: "Supprimer" do %>
                Supprimer
              <% end %>
            </td>
          </tr>
        <% end %>
        <%= line_chart [
  { name: "Poids (kg)", data: WeightEntry.group(:date).sum(:weight), yAxisIndex: 0, color: '#3498db' },
  { name: "Pas", data: WeightEntry.group(:date).sum(:steps), yAxisIndex: 1, color: '#e74c3c' }
], 
library: {
  yAxis: [
    { title: { text: "Poids (kg)", style: { color: '#3498db' } } }, # Axe principal
    { title: { text: "Pas", style: { color: '#e74c3c' } }, opposite: true } # Axe secondaire (droite)
  ],
  xAxis: { title: { text: "Date" } }
} %>


      </tbody>
    </table>
  </div>
</div>

src/app/views/weight_entries/new.html.erb
<div class="flex justify-center items-center">
    <div class="bg-white p-8 rounded-xl shadow-lg w-full max-w-md">
        <h1 class="text-2xl font-bold text-gray-800 mb-4 text-center">Ajouter un nouveau suivi de poids</h1>

        <%= form_with(model: @weight_entry, local: true) do |form| %>
            <% if @weight_entry.errors.any? %>
        <div class="alert alert-danger">
            <h4>Erreur</h4>
            <ul>
                <% @weight_entry.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="mb-4">
            <%= form.label :weight %>
            <%= form.number_field :weight, step: "0.1", placeholder: "Entrez votre poids"%>
        </div>

        <div class="mb-4">
            <%= form.label :steps, "Nombre de pas" %>
            <%= form.number_field :steps, placeholder: "Entrez votre nombre de pas", class: "w-full border rounded p-2"%>
        </div>
        
        <div class="mb-4">
            <%= form.label :date %>
            <%= form.date_field :date, placeholder: "Entrez la date de votre suivi de poids"%>
        </div>

        <div class="flex justify-end gap-2">
            <%= form.submit "Enregistrer", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>
            <%= link_to 'Retour', weight_entries_path , class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>

        </div>
        <% end %>

    </div>
</div>

src/app/views/weight_entries/show.html.erb
<div class="flex justify-center items-center">
    <div class="bg-white p-8 rounded-xl shadow-lg w-full max-w-md">
        <h1 class="text-2xl font-bold text-gray-800 mb-4 text-center">Détails</h1>
        
        <p class="text-gray-600">Poids : <span class="font-semibold text-gray-800"><%= @weight_entry.weight %></span></p>
        <p class="text-gray-600 mb-4">Pas : <span class="font-semibold text-gray-800"><%= @weight_entry.steps %></span></p>
        <p class="text-gray-600 mb-4">Date : <span class="font-semibold text-gray-800"><%= @weight_entry.date %></span></p>
        
        <div class="flex justify-end">
            <%= link_to 'Retour', weight_entries_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded transition duration-300" %>
        </div>
    </div>
</div>